name: Sync MDDB database

on:
  # Run this workflow every time there is a push with changes
  push:
    branches: [ master ]
  # Allow also to manually run the workflow from github for debugging purposes
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        description: 'Open an interactive sesion'
        default: false
        required: false

permissions:
  contents: write

jobs:
  sync-to-other-repos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.MDDB_REPOS }}

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      
      - name: Open debug session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug }}

      - name: Update other repositories
        run: |
          # Get the current commit here in the common repository
          updated_commit=$(git rev-parse HEAD)
          echo "Updated subtree last commit: $updated_commit"
          # Iterate MDDB repositores which use this code
          for repo in MDDB-REST-API
            do echo "Checking $repo"
            # Donwload the repository
            repo_url=https://github.com/mmb-irb/$repo.git
            repo_path="../$repo"
            git clone $repo_url $repo_path
            cd $repo_path
            # Check the latest commit of the common subtree
            last_commit=$(git subtree split --prefix=src/mddb-database)
            echo "  $repo subtree last commit: $last_commit"
            # If the repository is already up to date then skip it
            if [ "$last_commit" == "$updated_commit" ]; then
              echo "  $repo is already up to date"
              continue
            fi
            echo "  $repo must be updated"
            # We must set our identity again since we are in a new repository
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            # Otherwise pull the latest changes to the repository and then push to its remote
            # The message prevents git from asking for the message of the merge commit
            git subtree pull --prefix=src/mddb-database \
              https://github.com/mmb-irb/mddb-database.git master \
              --message 'automatic subtree merge'
            git push $repo_url master
            echo "  $repo has been updated"
          done
